# make PFunction tests

test:
	#cd PFunction && $(MAKE)
	cd commandline && $(MAKE)
	cd python && $(MAKE)
	cd continuum_plasticity && $(MAKE)

clean: 
	#cd PFunction && $(MAKE) clean
	cd commandline && $(MAKE) clean
	cd python && $(MAKE) clean
	cd continuum_plasticity && $(MAKE) clean
	cd testlib && $(MAKE) clean
